### ISSUE TITLE
How to disable dragging a specific box in list.

### ISSUE THREAD

**Issue by PoppyPham** [SortableJS/angular-sortablejs#10]
Hi

It good feature for me, but in angular 2 i use *ngFor to repeat over all box in box items array?
I want to the last box is fixed, cannot drag.
How can i configuration that.

Thanks,

**Comment by smnbbrv** [comment]
Hi @PoppyPham ,

you can easily configure that using `sortablejsOptions` `draggable` property, see the [original library properties](https://github.com/RubaXa/Sortable). E.g. add the special class to the items you want to sort:

```html
<div *ngFor="let item of items">
  <item1 [class.draggable]="isDraggable(item)"></item1>
  ...
</div>
```

Here your class `draggable` will be applied depending on the function result.

Now add your property to the `sortablejsOptions`:

```ts
import { SortablejsOptions } from 'angular-sortablejs';

export class MyComponent {

  public sortablejsOptions: SortablejsOptions = {
    draggable: '.draggable'
  };

  public isDraggable(item: any) {
    return true;
  }

}
```

Does this answer your question?
