### ISSUE TITLE
Preventing drop on another item in the same list

### ISSUE THREAD

**Issue by lehtiniemi** [SortableJS/angular-sortablejs#101]
I'm using sortablejs for reordering the list. The list is a bunch of Bootstrap 4 divs with class "col" on them so basically I'm reordering a layout by dragging the paragraphs.

When I drag the containers so that the other has time to move "out of the way", everything works, but if I drag an item onto another item, weird things happen. I think the code tries to merge all the character data of the div into the one I dropped it on. The cols also include toolbars that are not part of the item data but somehow these also get merged.

I would like to stop the behavior when the items are trying to merge and just limit it to the reordering (where the items move out of the way.

Is there something different going on when the sortable items are dragged on top of each other? Is there a way to prevent this action?

**Comment by smnbbrv** [comment]
Hi 

Please reproduce the problem on stackblitz or plunkr.

**Comment by smnbbrv** [comment]
unclear + inactivity => closing
