### ISSUE TITLE
How to import?

### ISSUE THREAD

**Issue by csjasonwong** [SortableJS/angular-sortablejs#108]
Hi, this may sound like a stupid question, but how do you import it in the app.module.ts?

It just said imports: [
  // ...
  SortablejsModule.forRoot({ animation: 150 }),
  // ...
]
but where is the import{} from '' on the top?

Thanks.

**Comment by smnbbrv** [comment]
@csjasonwong `import {SortablejsModule} from 'angular-sortablejs';`?

**Comment by csjasonwong** [comment]
Thanks
