### ISSUE TITLE
Problem with filename 

### ISSUE THREAD

**Issue by ronaldohoch** [SortableJS/angular-sortablejs#109]
Hello!
![image](https://user-images.githubusercontent.com/2287371/39836637-6ffb85b8-53aa-11e8-8aa4-2e30d4be6c50.png)

When using linux and angular-cli with "import { SortablejsModule } from 'angular-sortablejs';", it throw an error with file name, because linux is Case Sentitive...
![image](https://user-images.githubusercontent.com/2287371/39836673-8bd0e288-53aa-11e8-8aa7-f84bfa35aff9.png)

Can you help me?

**Comment by smnbbrv** [comment]
Hi,

not really as long as this comes from the original library... Please post it there.
