### ISSUE TITLE
issue with scrolling modal

### ISSUE THREAD

**Issue by mbowman6241** [SortableJS/angular-sortablejs#115]
I'm using angular-sortablejs v.2.5.2 to implement drag and drop in a modal. Its a nested array. The modal is opened via ngx-bootstap by calling the bsModalService.show(). I have no issues re arranging my array. 

My issue is this: 

when I use the default sortableJS options, nothing scrolls in the Modal, only the body behind the modal scrolls

      itemOptions: SortablejsOptions = {
         group: Items,
         handle: '.drag-handle',

Here is a small clip of my html:

    <div id=thisId">
    <ul [sortablejs]="[item]" [sortablejsOptions]="itemOptions">
	    <li *ngFor="let item of Items">
		    <div class="drag-handle">
			    <a><i class="handle"></i></a>
		    </div>
		    <div class="content">
			    <content-row></content-row>
		    </div>
	    </li>
    </ul>
    </div>

So I changed my SortablejsOptions to like:

      itemOptions: SortablejsOptions = {
         group: Items,
         handle: '.drag-handle',
         scroll: document.getElementById('thisId')
This solves the issue of the body scrolling, and scrolls the model. But now the item I am dragging is allowed to be dragged outside the browser window. I can even drag the item into the address bar as well as into the taskbar.

So then I set the SortableJsOptions to:

      itemOptions: SortablejsOptions = {
         group: Items,
         handle: '.drag-handle',
         scroll: document.getElementById('thisId')
         forceFallback:true,
         fallbackOnBody: true,
         fallbackClass: 'clone',

This solves the issues of the dragging item going outside the browser but i am not longer able to scroll. 

How do you configure the sortableJsOptions to drag and drop in the modal without going outside of the browser??

**Comment by smnbbrv** [comment]
hi @mbowman6241 

from what I can understand this is a typical behavior of the original library http://jsbin.com/kolisu/edit?html,js,output . I can drag the items anywhere.

**Comment by mbowman6241** [comment]
Hey @smnbbrv,

Thanks for getting back to me. If that is the case, do you know how or where I can set/create a container that the dragged item will stay in?

**Comment by smnbbrv** [comment]
I don't think this is anyhow possible because the dragged element is outside of the element's and even window's scope because it uses native draggable api, see detailed explanation here https://kryogenix.org/code/browser/custom-drag-image.html (and even here it goes outside browser).

The forcefallback you used disables it and that's why works, however I would recommend to stay with native HTML5 feature
