### ISSUE TITLE
router.navigation problem

### ISSUE THREAD

**Issue by kemalatila** [SortableJS/angular-sortablejs#119]
```
export class TestComponent {
  items_array: any;
  options: SortablejsOptions = {
    group: 'test',
    onAdd: (function (event) {
      const person_id = event.item.getAttribute('data-id');
      const data = {
        usr_id: person_id,
        from_process: event.from.id,
        to_process: event.to.id
      };
      this.http.post(this.apiUrl + 'persons/update_process/' + person_id, data);
      if (event.to.id === 'appointment_items') {
       this.router.navigate(['/customer-interview-card/', person_id]);
      }


    }).bind(this),
  };

```
I want to redirect users to another page on "onAdd" event. and its redirect but until I clicked the page. It dosen't complete redirection process and components dosen't work very well when page loaded. How can I solve this problem.

**Comment by smnbbrv** [comment]
did you try to inject `ApplicationRef` and run `applicationRef.tick();` inside your `onAdd`?

**Comment by kemalatila** [comment]
I tried now and dosen't work.

**Comment by smnbbrv** [comment]
Could you please make a simple reproduction of the problem on stackblitz?

**Comment by bhaskerchari** [comment]
Hi @kemalatila ,

Can you try the solution I suggested in the issue https://github.com/SortableJS/angular-sortablejs/issues/110 and let me know if that works for you as well?

Thanks,
Bhasker

**Comment by kemalatila** [comment]
My problem solved spontaneously when I moved my component into new ready template. if I experience the same problem I will benefit from your reference. Thank you for interested in.
