### ISSUE TITLE
OnAdd / Update / Remove Events

### ISSUE THREAD

**Issue by xaph0n** [SortableJS/angular-sortablejs#12]
Thanks for helping out with the other issue, and answering questions.  

When looking at updating everything, it looks like the events surfaced in these events, are drag events instead of the sortable js events.  I'm wondering if this is intentional, and if it is, is there some other way to grab the sortable event?

`sortOptions: SortablejsOptions = {
		animation: 200,
		group: 'cards',
		onEnd: function (evt) {
			console.log(evt); // surfaces the sortable event
		},
		onAdd: function (evt) {
			console.log(evt); // surfaces a dragable event so some data is lost
		}
	}`

**Comment by smnbbrv** [comment]
definitely a bug, try a new 1.0.1 version

**Comment by xaph0n** [comment]
That is working the way I would expect, thanks for the quick update.
