### ISSUE TITLE
Not able to get the libraries to load, using SystemJS loader

### ISSUE THREAD

**Issue by redevill** [SortableJS/angular-sortablejs#120]
Hello,

I am using Angular 4.x.x and a SystemJs loader.
Configuration I passed as per the end of the wiki:
  "map": {
    'angular-sortablejs': 'node_modules/angular-sortablejs/dist/',
    'sortablejs/Sortable.min': 'node_modules/sortablejs/Sortable.min.js'
  },
  "packages": {
    "app": {
      "defaultExtension": "js"
    },
    "angular-sortablejs": {
      "main": "index.js",
      "defaultExtension": "js"
    }
  }

Main module contains:
import { SortablejsModule } from 'angular-sortablejs';
and in the imports section  
SortablejsModule.forRoot({ animation: 150 })

In the component.ts file
import { SortablejsOptions } from 'angular-sortablejs';
In the component.html template file the following binding
<div #resultSortContainer [sortablejs]="results">

While I am able to "require" the Javascript file, the Angular wrapper eludes me.
SytemJS is resolving to a file that includes a "<" character, and then failing. Not sure how, because the mapped paths don't have any index.html type files in them...

Any help would be appreciated
Thanks
Eti

**Comment by redevill** [comment]
PS I did try the newer format with the maps contained within the packages, but still no joy.

**Comment by smnbbrv** [comment]
> includes a "<" character

sounds that some HTML file is served instead of JS...

**Comment by smnbbrv** [comment]
I think the html you get is your index.html. Typically this kind of error appears when the script file is not found and index.html is served instead as a 404 fallback. You should be able to see what systemjs is calling in the browser network console

**Comment by redevill** [comment]
Just realized, the docs only mention the addition to the imports array... but not the import statement itself - what is that supposed to look like?
I was assuming the default? - 
import { SortablejsModule } from 'angular-sortablejs';

**Comment by redevill** [comment]
All I can see from the console output is that systemjs is failing after trying to load my module (the one with the sortable in it)... does not give a paths tried... trying to find some more debugging input.

map-search:65 SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:9001/node_modules/systemjs/dist/system.src.js?1528915318058:2802:18)
    at http://localhost:9001/node_modules/systemjs/dist/system.src.js?1528915318058:3607:23
    at dynamicExecute (http://localhost:9001/node_modules/systemjs/dist/system.src.js?1528915318058:1138:28)
    at doEvaluate (http://localhost:9001/node_modules/systemjs/dist/system.src.js?1528915318058:1085:15)
    at ensureEvaluate (http://localhost:9001/node_modules/systemjs/dist/system.src.js?1528915318058:993:15)
    at http://localhost:9001/node_modules/systemjs/dist/system.src.js?1528915318058:1011:22
    at Object.eval (http://localhost:9001/app/mapSearch/mapSearch.module.js:41:28)
    at eval (http://localhost:9001/app/mapSearch/mapSearch.module.js:103:4)
    at eval (http://localhost:9001/app/mapSearch/mapSearch.module.js:104:3)

**Comment by smnbbrv** [comment]
you need to look at the network section of the browser.

![image](https://user-images.githubusercontent.com/13453858/41372174-cae05090-6f4c-11e8-9014-85a23d62f09a.png)

here you will be able to see the javascript files. Check EVERY of them, some is returning HTML

**Comment by redevill** [comment]
![image](https://user-images.githubusercontent.com/8999255/41374055-5ab1bf44-6f0f-11e8-842b-f44b455a8955.png)

Really odd... On the network tab it appears to be loading the library, but not from a location I'd expect.

**Comment by redevill** [comment]
Some progress... it is trying to load the submodules, but not appending the ".js"

![image](https://user-images.githubusercontent.com/8999255/41385377-6a9202d8-6f38-11e8-8708-fc15f47dc419.png)
Using
"map": {
    "angular-sortablejs": "node_modules/angular-sortablejs/dist/index.js"
  },

**Comment by redevill** [comment]
I have tried every systemjs configuration I can think of - your module won't load :(
Would very much like to use it - any help would be appreciated!

**Comment by redevill** [comment]
I think it should be something like this... according to the systemJS spec:
Conflict with other angular imports? a dash is considered a word boundary in reg exp ?!?

 "packages": {
    "angular-sortablejs": {
      "main": "index.js",
      "defaultExtension": "js",
      "map": {
        "angular-sortablejs": "node_modules/angular-sortablejs/dist/"
      }
    }
  }

Can you load it using systemJS?

**Comment by smnbbrv** [comment]
check this plunkr https://next.plnkr.co/edit/WcK824ulv9jOEOLODG3l?p=preview&utm_source=legacy&utm_medium=worker&utm_campaign=next&preview . The configuration is working here
