### ISSUE TITLE
Variable getting scoped inside onAddOriginal event in Angular

### ISSUE THREAD

**Issue by DarshanTeerth** [SortableJS/angular-sortablejs#123]
I am using the angular-sortablejs plugin for sorting of the list in my application. Here I have two lists, list A and list B. When I am trying to drop an item from List A to List B, I am triggering onAddOriginal event in list B.

where, in this event, I am changing a variable sortableWidget value to true. This variable value is getting scoped inside onAddOriginal event and I am not able to get the change value of the variable. Also not able to call methods, which will throw error, the method is not defined.

Here's my code:

```selectedWidget: boolean = false  ;
optionsForDroppableArea: SortablejsOptions = {
    group: {
        name: 'widgets',
        put: true,
        pull: true
    },
    onAddOriginal: function (evt) {
        this.selectedWidget = true;
        this.addRow();
    }
};
```
And when I am consoling the variable, I am getting the value as false and not as true.

```deleteRow(){
    console.log(this.selectedWidget);
} 
```
Is there any way I could declare a boolean variable as false. Then change the value to true and able to access this variable all over the code as true. In other words, can I make this variable globally scoped?

**Comment by smnbbrv** [comment]
You should use an arrow function instead of anonymous one

**Comment by DarshanTeerth** [comment]
Thanks, using arrow function solves the variable scoping issue, but still, I am getting "_this.addRow() is not a function" error.

**Comment by smnbbrv** [comment]
Then most likely there is no addRow function on your ‘this’
