### ISSUE TITLE
Cannot get directive to compile under Angular 6

### ISSUE THREAD

**Issue by signorello-john** [SortableJS/angular-sortablejs#124]
The program is very neat. However, I cannot get the directive to build under angular 6 / angular cli.

Does anybody have a working directive for angular 6?

**Comment by smnbbrv** [comment]
well, looks like everybody has a working directive :)

What is exactly the issue? Is there any error message? What command do you run? What is the issue?

**Comment by signorello-john** [comment]
I apologize. It works. Great piece of coding. Thanks
