### ISSUE TITLE
Drag drop not working properly with nested UL LI

### ISSUE THREAD

**Issue by gsinha** [SortableJS/angular-sortablejs#125]
I am using tree structure with nested ul li. Problem comes when I try to drag drop at the third level. I says "can not read sortable.. of null". I am using the below code. Please validate if I am using it correctly or missing something:

<ul class="agl-tree">
      <ng-template #recursiveList let-itemLst>
        <li *ngFor="let item of itemLst">
          <div [ngClass]="item.IsSelected?'item-highlighted':'item-highlighted1'">
            <a href="javascript:void(0);" class="add-item"><img src="/SB_Assets/images/addItem.png" /></a>
            <a href="javascript:void(0);" class="ex-col-arrow" [ngClass]="item.Level==0?'arrow-left-level1':item.Level==1?'arrow-left-level2':item.Level==2?'arrow-left-level3':'arrow-left-level4'" (click)="CollapseItem(item);" *ngIf="item.IsExpanded && item.Children!=null && item.Children.length > 0">
              <img src="/SB_Assets/images/arrow_down.png" />
            </a>
            <a href="javascript:void(0);" class="ex-col-arrow" [ngClass]="item.Level==0?'arrow-left-level1':item.Level==1?'arrow-left-level2':item.Level==2?'arrow-left-level3':'arrow-left-level4'" (click)="ExpandItem(item);" *ngIf="!item.IsExpanded && item.Children!=null && item.Children.length > 0">
              <img src="/SB_Assets/images/arrow_right_tree.png" />
            </a>
            <a href="javascript:void(0);" (click)="ItemClick(item);" class="level-strip" [ngClass]="item.Level==0?'orange-s':item.Level==1?'blue-s':item.Level==2?'green-s':'purple-s'">{{item.Title}}</a>
            <img src="/UX/Images/Common/SmallButtons/AttachmentIcon.png" alt="" *ngIf="item.HasAttachment" />
          </div>
          <ul *ngIf="item.Children!=null && item.Children.length > 0 && item.IsExpanded" [sortablejs]="item.Children" [sortablejsOptions]="options">
            <ng-container *ngTemplateOutlet="recursiveList; context:{ $implicit: item.Children }"></ng-container>
          </ul>
        </li>
      </ng-template>
      <div [sortablejs]="itemLst" [sortablejsOptions]="options">
        <ng-container *ngTemplateOutlet="recursiveList; context:{ $implicit: itemLst }"></ng-container>
      </div>
    </ul>

**Comment by gsinha** [comment]
`<ul class="agl-tree">
      <ng-template #recursiveList let-itemLst>
        <li *ngFor="let item of itemLst">
          <div [ngClass]="item.IsSelected?'item-highlighted':'item-highlighted1'">
            <a href="javascript:void(0);" class="add-item"><img src="/SB_Assets/images/addItem.png" /></a>
            <a href="javascript:void(0);" class="ex-col-arrow" [ngClass]="item.Level==0?'arrow-left-level1':item.Level==1?'arrow-left-level2':item.Level==2?'arrow-left-level3':'arrow-left-level4'" (click)="CollapseItem(item);" *ngIf="item.IsExpanded && item.Children!=null && item.Children.length > 0">
              <img src="/SB_Assets/images/arrow_down.png" />
            </a>
            <a href="javascript:void(0);" class="ex-col-arrow" [ngClass]="item.Level==0?'arrow-left-level1':item.Level==1?'arrow-left-level2':item.Level==2?'arrow-left-level3':'arrow-left-level4'" (click)="ExpandItem(item);" *ngIf="!item.IsExpanded && item.Children!=null && item.Children.length > 0">
              <img src="/SB_Assets/images/arrow_right_tree.png" />
            </a>
            <a href="javascript:void(0);" (click)="ItemClick(item);" class="level-strip" [ngClass]="item.Level==0?'orange-s':item.Level==1?'blue-s':item.Level==2?'green-s':'purple-s'">{{item.Title}}</a>
            <img src="/UX/Images/Common/SmallButtons/AttachmentIcon.png" alt="" *ngIf="item.HasAttachment" />
          </div>
          <ul *ngIf="item.Children!=null && item.Children.length > 0 && item.IsExpanded" [sortablejs]="item.Children" [sortablejsOptions]="options">
            <ng-container *ngTemplateOutlet="recursiveList; context:{ $implicit: item.Children }"></ng-container>
          </ul>
        </li>
      </ng-template>
      <div [sortablejs]="itemLst" [sortablejsOptions]="options">
        <ng-container *ngTemplateOutlet="recursiveList; context:{ $implicit: itemLst }"></ng-container>
      </div>
    </ul>`

**Comment by smnbbrv** [comment]
that's not really readable. Please create a stackblitz where you can reproduce the problem

**Comment by gsinha** [comment]
Sorry for the inconvenience. I make it more simple. If you drag between two lists (say two ULs) and you are dragging and dropping the last element (LI) from one list to another, then it throws exception. I have seen this problem in your own demo site. Please see the attached screenshot. 

![image](https://user-images.githubusercontent.com/485360/43977323-611c186e-9d01-11e8-9400-942184252d96.png)

**Comment by smnbbrv** [comment]
Closing in favor of #127
