### ISSUE TITLE
Angular-SortableJS in combination with Form Arrays

### ISSUE THREAD

**Issue by silamon** [SortableJS/angular-sortablejs#128]
We are having trouble to use this package in combination with Form Arrays. 

We have set up an example of what we are trying to achieve in a Stackblitz below: 
https://stackblitz.com/edit/angular-m1sokg

**First example**: A Form Array with 3 items and the possibility to drag-and-drop the items. 

**Second example**: A Form Array with 2 groups and 3 items in each group and the possibility to drag-and-drop the items in any of the groups.

The Form Array is for some reason not updated after a drag-and-drop of an item. In the second example, it does something after dragging an item into another group.  

We are using: 
- Angular v6.0.0
- RxJS v6.1.0
- Angular SortableJS v2.6.0
- SortableJS v1.7.0

**Comment by smnbbrv** [comment]
Hi,

you need to pass the `FormArray` instance to `[sortablejs]` instead of controls object. In other words, instead of `[sortablejs]="basicFormGroup.get('items').controls"` you need to pass [sortablejs]="basicFormGroup.get('items')". If you update all your examples correspondingly, you should see the result. Please let me know whether this helps.

**Comment by silamon** [comment]
Thank you very much for checking the examples. That resolves the issue.

**Comment by IZelenskiy** [comment]
> Hi,
> 
> you need to pass the `FormArray` instance to `[sortablejs]` instead of controls object. In other words, instead of `[sortablejs]="basicFormGroup.get('items').controls"` you need to pass [sortablejs]="basicFormGroup.get('items')". If you update all your examples correspondingly, you should see the result. Please let me know whether this helps.

Thanks for the explanation. You explanation has helped me even nowadays.
