### ISSUE TITLE
OriginalEvent is undefined on onStart handler

### ISSUE THREAD

**Issue by parasharrajat** [SortableJS/angular-sortablejs#151]
I want to access the original event to change the `dragImage`. I checked the docs on HTML5 drag N drop and found that we shoudl do this in `dragStart` event.
So while in sortable I am doing this in 'onStart' hook but 'originalEvent' is undefined.
`{
newIndex: undefined,
oldIndex: 0,
originalEvent: undefined,
returnValue: true,
srcElement: ...,
target: ...,
timeStamp: 2315630.495,
to: ...,
type: "start"
}
`

**Comment by smnbbrv** [comment]
Hi @parasharrajat 

the event is not anyhow modified in angular-sortablejs. You always receive the original sortablejs event.

**Comment by parasharrajat** [comment]
Yes ! this is `CustomEvent` of sortablejs but it's `originalEvent` property is `undefind`.
should I post this issue of sortablejs repo?

**Comment by smnbbrv** [comment]
> this is `CustomEvent` of sortablejs but it's `originalEvent` property is `undefind`.

nope, the event you receive is a normal sortablejs event "as is". The `CustomEvent` is nothing but an interface. The event data you posted above is sortablejs event.

> should I post this issue of sortablejs repo?

I thinks so :)

**Comment by parasharrajat** [comment]
Thanks a lot for your time.
