### ISSUE TITLE
update the options on onchoose event but it doesn't work until mouse up

### ISSUE THREAD

**Issue by Amanda1995pig** [SortableJS/angular-sortablejs#152]
Hi,
     I want to update the put attributes of group ，when I click the item.
I try to update the options in the onChoose event.And,I check it at the console ,the options have been changed when mouse down，but it does't work before mouse up. only do I click the item at the second time,it can be worked.  So I want to know how to make it works before mouse up.
                                                                                                                                                      Thank you

**Comment by benshabatnoam** [comment]
Hi @Amanda1995pig, did you manage to implement this behavior?
