### ISSUE TITLE
Button handle not working in Egde

### ISSUE THREAD

**Issue by piernik** [SortableJS/angular-sortablejs#156]
`handle` with `button` element is not working in Edge. `handle` with `div` is working. 

Here is gif. Div and button have class `sorting-handle` and sortable has options: ` [sortablejsOptions]="{handle: '.sorting-handle'}"`

![edge-sorting](https://user-images.githubusercontent.com/420691/55706352-4dd79b00-59e1-11e9-9f14-1ad0c42eed4b.gif)

**Comment by smnbbrv** [comment]
hi,

please post this at https://github.com/SortableJS/sortable
