### ISSUE TITLE
Indexes are not changing

### ISSUE THREAD

**Issue by thybak** [SortableJS/angular-sortablejs#16]
First of all thank you for your work. I guess that this module is being useful for everybody here.

I have to say that I read your readme carefully before writing this issue. But, although I was able to install this module and I could make changes client-side, these changes are not reflected in my model property, which is an object array. I followed your instructions by using [sortablejs]='-propertyName-' in the template, but it had no use for me. After changing the order of the elements, the array has the elements in the same position of the beginning in the model property, not in the view (where, in fact, they've changed).

Since I found this problem, I tried a workaround by using the SortableJsOptions. However, inside the event functions you don't have the same context of the Angular Component and you can't modify model properties.

I ran out of possibilities here, am I losing something in my reasoning?

**Comment by thybak** [comment]
OK, there's no issue at all. The problem is that I'm loading sortablejs before the observable populates the model. This observable is obtained from a webservice call, therefore it is a timing issue I have to solve in my code.

Sorry for the inconvenience of my *not* issue.

**Comment by smnbbrv** [comment]
Hi @thybak , it's good that it is solved. However it is going to be solved after ngOnChnages pull request https://github.com/SortableJS/angular-sortablejs/pull/15 is merged.

**Comment by smnbbrv** [comment]
Hi @thybak should be fixed with the latest version

**Comment by thybak** [comment]
I'm waiting NPM to release your 1.2.1 version to answer you if my original problem can be solved without initializing the array property in the model.

Thank you.

**Comment by smnbbrv** [comment]
Hi @thybak , sorry for delay, now it should be published. Try again, please

**Comment by thybak** [comment]
Works like a charm! Good job 👍

Thank you again for your work along the SortableJS team, @smnbbrv ;)
