### ISSUE TITLE
change input array in ngOnChanges

### ISSUE THREAD

**Issue by smnbbrv** [SortableJS/angular-sortablejs#17]
Currently the input array is retrieved only when instantiated. The reference to array is passed, so the changes in array items are tracked as they should; however when the **reference** to array is changed, this won't trigger the items change, see #16.

**Comment by ardf69** [comment]
Maybe what I found is related. According to the code if items is undefined at the start the onAdd, onRemove and onUpdate callbacks aren't set. If after that I set items the 3 callbacks remains unset and so the data sorting doesn't work.

**Comment by smnbbrv** [comment]
Hi @ardf69 

could you test it now with 1.2.1? Please, let me know if it does not work

**Comment by ardf69** [comment]
Now it seems to work. Thank you.

Ciao Angelo
