### ISSUE TITLE
SortablejsModule is not an NgModule

### ISSUE THREAD

**Issue by keithotto** [SortableJS/angular-sortablejs#18]
I'm working on a project using Angular-CLI, which uses webpack. I installed this module from npm following the instructions in the readme. When I import the module into my application module and use the CLI's 'ng serve' to build and run the site locally i get the following error:

> ERROR in SortablejsModule is not an NgModule

> ERROR in ./~/angular-sortablejs/index.d.ts
> Module build failed: Error: Debug Failure. False expression: Output generation failed
>     at Object.assert

**Comment by smnbbrv** [comment]
hi @keithotto @drew-moore

could you, please, provide me with a plunkr / repo where I can see the issue? This seems like a particular project configuration problem

**Comment by smnbbrv** [comment]
@keithotto could you validate whether this branch fixes your issue?

**Comment by BrainCrumbz** [comment]
Don't know where did the original comment end up, but yes, will definitely give it a spin. Thank you!

**Comment by smnbbrv** [comment]
@BrainCrumbz I moved it to the proper issue #19 :) at first made it by mistake here

**Comment by keithotto** [comment]
Hey sorry I'll test the update as soon as I get a chance. Been out for xmas.

**Comment by smnbbrv** [comment]
@keithotto no problem, have nice holidays! After you come back, just try the latest version

**Comment by keithotto** [comment]
Just following up: I updated to 1.3.1 and it now appears to be working. Not getting the error when compiling any longer. Thanks!
