### ISSUE TITLE
Unexpected value SortablejsModule imported by module

### ISSUE THREAD

**Issue by GiuseppePiscopo** [SortableJS/angular-sortablejs#19]
Hi there. Thanks for this library, first of all.

I'm finding an issue I can't resolve when building a project in AOT mode (everything goes fine in JIT build). Not sure this is the same as #18 , error messages seem different. At compile time I get an error:

> Error: Unexpected value 'SortablejsModule' imported by the module 'MyCustomModule'
    at xxxx\node_modules\@angular\compiler\bundles\compiler.umd.js:17768:46
    ....

This is with webpack 2.1.0-beta.25 and angular 2.3.1. Tried upgrading to latest angular 2.4.1 and error is still there, just reworded:

> Unexpected value 'SortablejsModule in xxxx/node_modules/angular-sortablejs/index.d.ts' imported by the module 'MyCustomModule in yyyy/my-module.ts'

I've met similar issues with other libraries I was depending on, and very often they are related to the library not being compiled through ngc (or Angular CLI), so there's no `metadata.json` generated file. See e.g.  for [ng2-bs3-modal](https://github.com/dougludlow/ng2-bs3-modal/issues/105#issuecomment-247388992), [angular-pipes](https://github.com/fknop/angular-pipes/issues/34), or [others](https://github.com/angular/angular/issues/11438). Other times it can be also due to some provider not being correctly exposed for AOT, as in [ng2-redux](https://github.com/angular-redux/ng2-redux/issues/228)

Has anyone met this problem before? Sorry for not providing a repro project yet, hopefully the references might give some hint to start.

**Comment by smnbbrv** [comment]
hi @GiuseppePiscopo 

could it also be connected to #18 ? The `ngc` is a good hint, probably fixes them both

**Comment by GiuseppePiscopo** [comment]
Would you consider a PR, even if partial and work-in-progress, to start moving to AOT build with ngc?

**Comment by smnbbrv** [comment]
Yes of course, PRs always welcome :) We can try it on a separate branch with prerelease versions that you can test it with the real projects

**Comment by GiuseppePiscopo** [comment]
Please have a (thorough?) look at #20 . 

Contrary to what I said before, apparently that is not so partial. I tried in project depending on this library, by manually swapping downloaded `node_modules\angular-sortablejs` with the output from `npm pack`. All goes fine both at compile time and runtime.

**Comment by smnbbrv** [comment]
Hi @GiuseppePiscopo @BrainCrumbz

the version 1.3.0-0 is published. I tried it with my projects, seems to work nicely.

Could you test it with yours and let me know whether I can create a normal 1.3.0?

**Comment by BrainCrumbz** [comment]
Green light for me

**Comment by smnbbrv** [comment]
@BrainCrumbz thank you guys for the effort and improvements you've done! Now is published as 1.3.0
