### ISSUE TITLE
Cannot find module / IDE shows error, too

### ISSUE THREAD

**Issue by patrickbussmann** [SortableJS/angular-sortablejs#21]
Hey guys,

I wanted to implement this nice sortable into my project.
But after installing it I get this errors.

	TypeScript error: node_modules/angular-sortablejs/dist/index.d.ts(1,15): Error TS2307: Cannot find module './src/sortablejs-options'.
	TypeScript error: node_modules/angular-sortablejs/dist/src/sortablejs.module.d.ts(1,35): Error TS2307: Cannot find module './sortablejs-options'.

And my IDE (WebStorm) shows me the same if I open the file `node_modules/angular-sortablejs/dist/index.d.ts`.

![image](https://cloud.githubusercontent.com/assets/15617021/21534740/914e19ea-cd6b-11e6-9ecb-6cce8c214c55.png)

Same with module file `node_modules/angular-sortablejs/dist/src/sortablejs.module.d.ts`

![image](https://cloud.githubusercontent.com/assets/15617021/21534742/9ace656a-cd6b-11e6-97a3-9e9c71098de3.png)

Don't know if this is a configuration issue or if this is related to #18.

And.... Happy New Year! :tada:

**Comment by BrainCrumbz** [comment]
Yeah, can confirm this as well. We see the same error highlighed in VS Code, and webpack output says the same:

> [default] xxxx\node_modules\angular-sortablejs\dist\index.d.ts:1:15
    Cannot find module './src/sortablejs-options'.
[default] xxxx\node_modules\angular-sortablejs\dist\src\sortablejs.module.d.ts:1:35
    Cannot find module './sortablejs-options'.
[default] xxxx\src\crm-backend\view\field-list\field-list.component.ts:7:10
    Module '"xxxx/node_modules/angular-sortablejs/dist/index"' has no exported member 'SortablejsOptions'.
[default] Checking finished with 3 errors

Maybe some change has been introduced between 1.3.0-0 and 1.3.0 ?

**Comment by BrainCrumbz** [comment]
I think I spotted at least something strange. In commit [07161f93](https://github.com/SortableJS/angular-sortablejs/commit/07161f938a7a4c955efbc2a759cb56d5ed1d00db) the options interface has been moved to its own file, `sortablejs-options.d.ts` but I think that has the wrong extension.

`.d.ts` files should be only intended as output artifacts, generated by TS compilation, and they work as declaration for package users (including IDEs), when they only have JS implementation left, no actual TS. They're part of the {`.d.ts`, `.metadata.json`, `.map`} tuple that is needed when consuming a library from ng2 + TS.

If all that makes sense, the proper name for that file should be `sortablejs-options.ts`, which should then generate all its outputs, as any other TS file.

**Comment by smnbbrv** [comment]
@BrainCrumbz you are right, fixed it with 1.3.1

I hope it is the last dinosaur :) Happy New Year guys!

**Comment by BrainCrumbz** [comment]
Cool. Happy New Year to you too! Cheers

**Comment by BBaysinger** [comment]
Is this back? What am I doing wrong here?: https://github.com/SortableJS/angular-sortablejs/issues/46

**Comment by JamboBuenna** [comment]
I'm currently seeing this now for angular 5 getting 
"Cannot find module 'angular-sortable.js'." I can resolve this only by running the install scripts on the specific machine. 

npm install --save sortablejs && npm install --save angular-sortablejs

**Comment by smnbbrv** [comment]
And... what is the problem? :D once you installed it on one machine you need to run simple `npm install` on other machines. This is how npm works

**Comment by JamboBuenna** [comment]
npm install doesn't update it on the other machines, only a specified install.

**Comment by smnbbrv** [comment]
this is really weird... To me it sounds like `package.json` does not get updated which is weird. But unfortunately I cannot help here. The libraries are published and work perfectly fine on any machine I have... And you are actually the really first with an issue like that.

This is definitely an NPM issue. The best I can propose is after you do `npm install --save sortablejs && npm install --save angular-sortablejs` try to look inside of the package.json to see whether the dependencies were added to `dependencies`. If they were - commit package.json and package-lock.json and pull it on other machines and `npm install` must install them. If they are not added to the dependencies then it is really weird and also should not happen

**Comment by JamboBuenna** [comment]
Node modules was checked into git. :-( 

Thank you so much for the support, sorry for the stupid mistake 👍

**Comment by smnbbrv** [comment]
That's fine, happens :)

**Comment by bijay-singh** [comment]
> npm install --save sortablejs && npm install --save angular-sortablejs

Even I was facing this issue. Thanks a lot, your solution helped me :)
