### ISSUE TITLE
Can't resolve module SortablejsDirective

### ISSUE THREAD

**Issue by thebarada** [SortableJS/angular-sortablejs#22]
While compilation with **ngc** I'm getting error

`
can't resolve module ./sortablejs.directive from node_modules/angular-sortablejs/dist/src/sortablejs.module.d.ts
Error: Cannot read property 'SortablejsDirective' of undefined, resolving symbol SortablejsModule in node_modules/angular-sortablejs/dist/src/sortablejs.module.d.ts, resolving symbol SortablejsModule in node_modules/angular-sortablejs/dist/src/sortablejs.module.d.ts
`

**Comment by thebarada** [comment]
@smnbbrv take a look at https://github.com/SortableJS/angular-sortablejs/pull/23

**Comment by smnbbrv** [comment]
Hi @thebarada 

sorry for delay, the holidays :)

I cannot understand why would you need to have `SortablejsDirective` exported anywhere. It is a part of the `SortablejsModule` and it is not exported with `exportAs` statement. It is not complicated to export it anyway but I need to know what and why should be supported in the future.

`ngc` was implemented within #19 and had no issues for the other guys. Could you, please, validate your code?

**Comment by CamusAran** [comment]
Getting the same error, using angular-cli 1.0.0-beta.22-1 / angular 2.2.3. Exporting SortablejsDirective like in https://github.com/SortableJS/angular-sortablejs/pull/23 fixes it.

**Comment by smnbbrv** [comment]
@thebarada  @CamusAran do you have a repo which reproduces this?

**Comment by smnbbrv** [comment]
closed; inactivity
