### ISSUE TITLE
Unmount Plugins on ngDestroy

### ISSUE THREAD

**Issue by earlvhin** [SortableJS/angular-sortablejs#249]
Hello, I am getting an Error

`Error: Sortable: Cannot mount plugin multiDrag more than once`
 
 This is everytime I load the component that uses SortableJS.
 
 I wonder If its possible to have an "unmount" feature

 ` ngOnDestory() {
         Sortable.unmount(MultiDrag()) 
 }`

**Comment by Mumma6** [comment]
We had the same problem with SortableJS
Try add it in a try catch

`try {
  Sortable?.mount(new MultiDrag())
} catch (error) {

}`
