### ISSUE TITLE
Issue with touch input (chrome)

### ISSUE THREAD

**Issue by keithotto** [SortableJS/angular-sortablejs#25]
I'm encountering an issue where the drag events seem to stop registering. So far in my test this is only happening with touch input. I can reproduce it in Chrome on my Android phone, and also in the Chrome desktop browser with the device simulation in the developer tools turned on.

What seems to be happening is I will start dragging an item, and when I move down to the next item which would trigger the swapping of the two items in the list, it seems to lose the drag tracking, and the ghosted element will freeze in place and stop responding to mouse movement. If I let go and then click on the element the ghost image will disappear.

I have my test page running at: [http://dev.lumoplay.com/sortable-test](http://dev.lumoplay.com/sortable-test)

I attached an image of what it looks like when it stops responding and the ghosted image freezes in place. I have to stop dragging, and click once on the page which seems to reset it.

It doesn't happen every time I drag an element, but it seems to be pretty frequent.

![drag_bug](https://cloud.githubusercontent.com/assets/17461410/21650987/7628775e-d26c-11e6-8618-279e1a4d041e.PNG)

**Comment by smnbbrv** [comment]
Hi @keithotto 

this library is just a port of original sortablejs for angular2. Any bug with browser support should go to the original https://github.com/RubaXa/Sortable

What I can propose is using the latest version 1.5.0-rc1 (see `npm info sortablejs`), 1.4.2 has lots of known issues. If this does not solve your problem (I hope it does) you can open an issue there
