### ISSUE TITLE
Get rid of `@angular/forms`

### ISSUE THREAD

**Issue by artaommahe** [SortableJS/angular-sortablejs#26]
`@angular/forms` is not primary angular module and can be skipped in app that uses `angular-sortable` (ReactiveForms can be used or no Forms module at all). But this lib uses it and it increases final bundle size.

**Comment by smnbbrv** [comment]
Hi @artaommahe 

that's a good idea, probably we can recognise the FormArray with a duck-typing instead of a direct match.

**Comment by smnbbrv** [comment]
released with 1.3.2
