### ISSUE TITLE
Draggable handle not working in Firefox and Edge, not in Chrome

### ISSUE THREAD

**Issue by BrainCrumbz** [SortableJS/angular-sortablejs#27]
Hi there, hope this is the right place to ask. 
We have an instance of *angular-sortablejs* working good in Chrome. This is the main gist of list component template:

```html
<div [sortablejs] [sortablejsOptions]="dragOptions">
  <div class="list-group-item"
      *ngFor="let item of listItems; let index = index">

      <customListItem *ngIf="!item.isEditing"
          [field]="item.field" [disabled]="actionsDisabled"
          (edit)="onListItemEdit(index)" (remove)="onListItemRemove(index)">
      </customListItem>

      <customEditItem *ngIf="item.isEditing"
          [field]="item.field" [uniqueId]="index" [disabled]="actionsDisabled"
          [allFields]="allFields"
          (confirm)="onListItemEditConfirm(index, $event)" (cancel)="onListItemEditCancel(index)">
      </customEditItem>

  </div><!-- list-group-item -->
</div>
```

The custom item template is initially created within DOM, as `item.isEditing` is initially false, so `*ngIf` is set to true. Here are the drag options set, constants: 

```ts
this.dragOptions = {
  onEnd: this.onListItemDragEnd.bind(this),
  handle: '.drag-handle',
};
```

Within list item component template, there's a button with `drag-handle` class:

```html
<div class="row">

  <!-- ... item fields ... -->

  <div class="col-md-2">
    <span class="pull-right">
      <!-- this is the drag button -->
      <button type="button" class="btn btn-xs btn-default drag-handle"
              [disabled]="actionsDisabled">
        <span class="glyphicon glyphicon-sort"></span>
        <span class="sr-only">Drag</span>
      </button>
      
      <button type="button" class="btn btn-xs btn-primary" (click)="onEdit()"
              [disabled]="actionsDisabled">
        <span class="glyphicon glyphicon-pencil"></span>
        <span class="sr-only">Edit</span>
      </button>
      
      <button type="button" class="btn btn-xs btn-warning" (click)="onRemove()"
              [disabled]="actionsDisabled">
        <span class="glyphicon glyphicon-minus"></span>
        <span class="sr-only">Delete</span>
      </button>
    </span>
  </div>

</div><!-- row -->
```

When in Firefox or Edge, no item seems to be draggable. The drag handle receives focus (on Firefox it looks bordered), but the item stays there. From inspection, I can see `sortable-chosen` class and `draggable="true"` attribute being set on item, but visually nothing changes.

Here there's a screencast trying to capture the issue:

![drag-failed](https://cloud.githubusercontent.com/assets/3185573/21821907/8c626fb2-d775-11e6-9fd9-009dee3c0771.gif)

Is there anyone aware of differences in behaviour among Chrome, Firefox and Edge on this side?

**Comment by smnbbrv** [comment]
Hi @BrainCrumbz 

I'm not sure there is any difference for the browsers here... What's done in `angular-sortablejs` is just a directive which operates with the model, it listens to the same events etc. 

The only thing I can advice here is trying to debug the `sortablejs` original library files from the `node_modules`. That's how I usually solved things like this...

There is no automatic testing here, I can't really imagine how to correctly test the dragging behavior in different browsers automatically.

**Comment by BrainCrumbz** [comment]
Hi @smnbbrv , thanks for clarifying (and excuse for late reply). To gain a better understanding, by any chance:

1. do you know about a ready-made plunker with angular-sortablejs? That's just to avoid starting from scratch, and avoid any issue that might be related to our project

1. do you have any pointer into *sortablejs* original source code, where to start debugging an issue like this?

Thanks in any case

**Comment by smnbbrv** [comment]
Hi @BrainCrumbz 

I didn't  create any yet, would be good to have one.

Debugging *sortablejs* is hard. It has many fallbacks, browser related code etc. so the issue could be nearly at any line... I'm not strong at the original library, maybe ask @RubaXa to help you out

**Comment by BrainCrumbz** [comment]
Tried putting up a plunker, starting from one of the latest angular + typescript seed plunkers. As for other npm modules, angular-sortable.js is referenced from [unpkg.com](http://unpkg.com/).

In *app.ts*, as soon as `SortablejsModule` is added to `@NgModule.imports` array, the app breaks and console is not helping in understanding what goes wrong. If you want to have a look, [here it is](https://plnkr.co/edit/ugp5Yg?p=preview).

Anyway, this of plunker is a side issue. Main point is still trying to reproduce the issue with a seed project.

**Comment by smnbbrv** [comment]
@BrainCrumbz I couldn't have noticed that you use `sortablejs@1.4.2` in the plunkr which is known for many issues. Have you tried to override it with `sortablejs@1.5.0-rc1`?

**Comment by BrainCrumbz** [comment]
Hi there, thanks for pointing that out, will give that a spin right away. That version is the one I found when looking into angular-sortablejs own dependencies in its `package.json`. So, if I got it right, basically is the one our project is including because of angular-sortablejs.

**Comment by BrainCrumbz** [comment]
No luck, runtime error shows up as soon as angular-sortablejs module is added to import list:

> Error: (SystemJS) XHR error (500 Internal Server Error) loading https://unpkg.com/angular-sortablejs@1.3.1/dist/index.js/index.js
	patchProperty/desc.set/wrapFn@https://unpkg.com/zone.js@0.6.21/dist/zone.js:628:26
	ZoneDelegate.prototype.invokeTask@https://unpkg.com/zone.js@0.6.21/dist/zone.js:225:23
	Zone.prototype.runTask@https://unpkg.com/zone.js@0.6.21/dist/zone.js:125:28
	ZoneTask/this.invoke@https://unpkg.com/zone.js@0.6.21/dist/zone.js:293:28
>	
>	Error loading https://unpkg.com/angular-sortablejs@1.3.1/dist/index.js/index.js as "angular-sortablejs" from https://run.plnkr.co/yPl1nTMGWBPrEANT/src/app.ts

**Comment by smnbbrv** [comment]
@BrainCrumbz no, I mean did you try it on your local machine to fix the original issue? :)

**Comment by BrainCrumbz** [comment]
Tried [this workaround](https://github.com/RubaXa/Sortable/issues/957) in v1.5.0-rc1 and it worked. Not sure if that also works with the version currently shipping with angular-sortablejs.

BTW, it seems like angular-sortablejs installed package holds a local `node_modules` subdirectory, with a local `sortablejs` directory too. Is that intentional? Shouldn't that be listed as a dependency or peerDependency, and let npm install it?

Cheers

**Comment by smnbbrv** [comment]
@BrainCrumbz the version ^1.4.2 is shipped with angular-sortablejs, so whenever non-rc version is released everybody will get a modern one.

**Comment by smnbbrv** [comment]
I close this I guess

**Comment by waspar** [comment]
Still actual for me the version 1.7.0
