### ISSUE TITLE
ctorParameters.map is not a function

### ISSUE THREAD

**Issue by baucez** [SortableJS/angular-sortablejs#28]
When I add the SortablejsModule to the imports and run the application I get this error:
Uncaught TypeError: ctorParameters.map is not a function

How can be fixed?

**Comment by smnbbrv** [comment]
Please, give more details. The error says literally nothing.

**Comment by baucez** [comment]
Sorry.. I'm a newbie on angular2
I just installed through npm.
I use webpack so according to the installation tutorial there is nothing to configure.
Everything looks good but as soon as I add SortablejsModule in the import section of my app module (without using the module in the entire application) I get the error.

Am I missing a part of the configuration?

**Comment by smnbbrv** [comment]
Hi @baucez 

I think there is either some versions incompatibility or maybe a setup problem... If you could share your setup via e.g. a git repo I could have a look there. Otherwise it is really hard to find out what the problem is

**Comment by gavbaa** [comment]
I experienced this issue today on an Angular 2.0.0 project.  Upgrading to Angular 2.4.3 resolved it for me, so I agree that's it's a versioning issue somewhere along the way, outside of this package.

**Comment by smnbbrv** [comment]
Hi @gavbaa 

thanks for the information!

@baucez does this fix the issue for you?

**Comment by smnbbrv** [comment]
ok, assuming it as fixed
