### ISSUE TITLE
Cannot access Component's methods from OnUpdate

### ISSUE THREAD

**Issue by MarcAragones** [SortableJS/angular-sortablejs#32]
I want to handle the list changes and send them to a server. However, `this` does not have the Component's context.

Error example: [Plunker](https://plnkr.co/edit/9PFa7cUJoxjWR9yvaMT9)

```typescript
export class App {
  name:string;
  items: string[] = [1, 2, 3, 4, 5];
  
  postChangesToServer() {
    // POST items to server
  }
  
  options: SortablejsOptions = {
    onUpdate: function (event: any) {
        console.log('onUpdate start');
        this.postChangesToServer(); // <-- Crashes here
        console.log('onUpdate end');
      }
    }
  };
  
}
```

**Comment by MarcAragones** [comment]
Finally, I could get it: [Plunker](https://plnkr.co/edit/hC7IkBaZwnpupvsjm6al).

I had to add the component to the `options` variable:

```typescript
export class App {
  name:string;
  items: string[] = [1, 2, 3, 4, 5];
  
  postChangesToServer() {
    console.log('postChangesToServer called!');
  }
  
  options: SortablejsOptions = {
    myComponent: this,
    onUpdate: function (event: any) {
        this.options.myComponent.postChangesToServer();
    }
  };
  
}
```

**Comment by haisaco** [comment]
I add same you but it have issue
Type '{ myComponent: this; onUpdate: (event: any) => void; }' is not assignable to type 'SortablejsOptions'.
  Object literal may only specify known properties, and 'myComponent' does not exist in type 'SortablejsOptions'

**Comment by haisaco** [comment]
I just fixed it:
`export class App {
  name:string;
  items: string[] = [1, 2, 3, 4, 5];
  
  postChangesToServer() {
    console.log('postChangesToServer called!');
  }
  
  options: SortablejsOptions = {
    onUpdate: function (event: any) {
        this.App.prototype.postChangesToServer();
    }
  };
  
}`

**Comment by haisaco** [comment]
It worked
but I can't get value from class App
example:
```
export class App {
  name:string = 'demo test';
  items: string[] = [1, 2, 3, 4, 5];
  
  postChangesToServer() {
    console.log(name);
  }
  options: SortablejsOptions = {
    myComponent: this,
    onUpdate: function (event: any) {
        this.options.myComponent.postChangesToServer();
    }
  };
}
```
not get value name??

**Comment by smnbbrv** [comment]
hi @MarcAragones 

This should work correctly
```ts
export class App {
  name:string = 'demo test';
  items: string[] = [1, 2, 3, 4, 5];
  
  postChangesToServer() {
    console.log(name);
  }
  options: SortablejsOptions = {
    myComponent: this,
    onUpdate: (event: any) => {
        this.options.myComponent.postChangesToServer();
    }
  };
}
```

**Comment by haisaco** [comment]
Hi @smnbbrv I edit for you but I have issue
Type '{ myComponent: this; onUpdate: (event: any) => void; }' is not assignable to type 'SortablejsOptions'.
  Object literal may only specify known properties, and 'myComponent' does not exist in type 'SortablejsOptions'

**Comment by smnbbrv** [comment]
ehm. That's your code, I don't know why you use it there :D Just remove it

```ts
constructor() {
     this.options = {
       onUpdate: (event: any) => {
         this.options.myComponent.postChangesToServer();
       }
     };
   }
```

**Comment by haisaco** [comment]
when I remove it
Property 'myComponent' does not exist on type 'SortablejsOptions'.
is my code 
```
constructor() {
     this.options = {
       onUpdate: (event: any) => {
         this.options.myComponent.postChangesToServer();
       }
     };
   }
```

**Comment by smnbbrv** [comment]
What about just 

```ts
constructor() {
     this.options = {
       onUpdate: (event: any) => {
         this.postChangesToServer();
       }
     };
   }
```

?

**Comment by haisaco** [comment]
It ok! 👍
