### ISSUE TITLE
How to use onUpdate method 

### ISSUE THREAD

**Issue by jeewendrakumar** [SortableJS/angular-sortablejs#33]
Hi Team,

I have to call another function which passes the new index of the element where w are getting from onUpdate(event.newIndex)..
How to call the onUpdate method..?
Example:
```
<ul [sortablejs]="items">
<li (onUpdate)=changeIndex(event)>
</li>
<ul>
```

**Comment by haisaco** [comment]
It same #32

**Comment by smnbbrv** [comment]
Hi @jeewendrakumar 

I assume @haisaco is right here, just try the same approach
