### ISSUE TITLE
onUpdate didn't runs into Angular

### ISSUE THREAD

**Issue by kamaliev** [SortableJS/angular-sortablejs#37]
Hi.

I have some configuration with onUpdate, where I'm have Angular function
<img width="613" alt="2017-04-04 15 10 37" src="https://cloud.githubusercontent.com/assets/9512672/24655987/3bfcf43c-1949-11e7-9216-c11c64a80fc4.png">

Angular method
<img width="294" alt="2017-04-04 15 13 41" src="https://cloud.githubusercontent.com/assets/9512672/24656013/51091284-1949-11e7-980c-2a51f87366e0.png">

When I update my list from drag&drop, I has this error
<img width="427" alt="2017-04-04 15 15 14" src="https://cloud.githubusercontent.com/assets/9512672/24656063/8aeb0f84-1949-11e7-9457-0f2ea63a2b72.png">

How do I run onUpdate inside Angular environment?

**Comment by kamaliev** [comment]
#32 
Please add this example to documentation.

**Comment by smnbbrv** [comment]
Hi @kamaliev 

could you add it and a make a pull request?

**Comment by kamaliev** [comment]
Hi @smnbbrv 
Yes I could.
If you will give me access to change documentation.

**Comment by smnbbrv** [comment]
@kamaliev you can make a pull request, you don't need to have any access to do that
