### ISSUE TITLE
Problems with webpack when using angular2-webpack-starter

### ISSUE THREAD

**Issue by f1lon** [SortableJS/angular-sortablejs#4]
It emmits errors like 

> WARNING in ./~/angular-sortablejs/index.js
> Cannot find source file 'index.ts': Error: Cannot resolve 'file' or 'directory' ./index.ts in C:\Users\filonov\Desktop\git-git\admin-panel\node_modules\angular-sortablejs

To solve that
`helpers.root('node_modules/angular-sortablejs')`
should be added to config/webpack.common.js#source-map-loader

**Comment by smnbbrv** [comment]
just tried with the newest versions, no warning any longer. If the issue still exists, please let me know
