### ISSUE TITLE
TypeError: Sortable is not a constructor

### ISSUE THREAD

**Issue by FlorKaucic** [SortableJS/angular-sortablejs#42]
I'm getting this error after updating to **ng2 4.0.1** 

I ran this: `npm install --save sortablejs && npm install --save angular-sortablejs`

And changed the systemjs configuration as it was not working as it was before. Now its:
```
var map = {
  'angular-sortablejs': 'node_modules/angular-sortablejs/dist/',
  'sortablejs/Sortable.min': 'node_modules/sortablejs/Sortable.min.js',
}
```
instead of:
```
var map = {
  // ...
  'angular-sortablejs': 'node_modules/angular-sortablejs/dist/',
  'sortablejs': 'node_modules/sortablejs/Sortable.js',
  // ...
};
```

**Comment by smnbbrv** [comment]
Hi @FlorKaucic 

is it a typescript error, right?

**Comment by FlorKaucic** [comment]
Hi @smnbbrv, yeah, I think it's a typescript error. But appearently it could be related to the imports order. I don't know if that's the case. 
Do you know anything that I could be forgetting for it to work? 
I'm importing the modules in the places I'm using it (and it was working before updating to Angular 2 4.0.1 and the latest version of sortablejs)

**Comment by smnbbrv** [comment]
Hi @FlorKaucic 

it could be everything... 😁

There was a switch from `require('sortablejs')` to ES6 `import`, that might be the case.

Do you have some public available repo where it can be reproduced?

**Comment by FlorKaucic** [comment]
Hey @smnbbrv  I found the fix, I'm creating a PR for you to see it.
The reason I was getting that error is that appearently now to create a `new Sortable object` using sortablejs, you need to use `Sortable.create(...)` function.
Also, I think the mapping config that I changed it's something that's causing trouble too (I think it might be what it's happening in #44) , anyway, I updated the README file with that config. 
I hope this helps, thank you for porting this to Angular2! :D It's great! :)
