### ISSUE TITLE
Polymer.dom is not a function in Firefox

### ISSUE THREAD

**Issue by ajinkyau** [SortableJS/angular-sortablejs#43]
Hi,

I am using "angular-sortablejs": "^1.3.2" in my angular 2 project.

When in Firefox, on trying to drag elements I receive an error:

TypeError: Polymer.dom is not a function[Learn More]  vendor.bundle.js:192570:7
	_clone http://localhost:4200/vendor.bundle.js:192570:7
	sortableFactory/Sortable.prototype._onDragStart http://localhost:4200/vendor.bundle.js:191783:15
	bound  self-hosted
	[579]/</</ZoneDelegate.prototype.invokeTask http://localhost:4200/polyfills.bundle.js:5779:17
	[579]/</</Zone.prototype.runTask http://localhost:4200/polyfills.bundle.js:5578:28
	ZoneTask/this.invoke http://localhost:4200/polyfills.bundle.js:5832:28

Which breaks the drag functionality on firefox.

Also, tried using "forceFallback: true / false" in options defined in my .ts file but the above issue persists.

This works fine on chrome without any issues.

**Comment by sumedh908** [comment]
I am having the same issue using version "angular-sortablejs": "^1.3.2". Not working in IE11 as well.

**Comment by smnbbrv** [comment]
hi @ajinkyau @sumedh908 

I think this is an issue of the original library and something is wrong with the Polymer and sortablejs versions.

We don't use Polymer on this side, but sortablejs does, see https://github.com/RubaXa/Sortable/blob/master/Sortable.js#L69.

Please, post the solution if you find one...
