### ISSUE TITLE
XHR error (404 Not Found) loading http://localhost:6061/traceur

### ISSUE THREAD

**Issue by leerenold** [SortableJS/angular-sortablejs#44]
Get this error when using angular-sortablejs .
Solutions provided for this kind of error is to refer .umd.js instead of index.js. But angular-sortablejs doesn't provide .umd.js .
Using angular 4.x. Installed with the steps provided.

My System.config

System.config({
                paths: {
                    'npm:': 'lib/'
                },
                map: {
                    app: 'app',
                    '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
                    '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
                    '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
                    '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
                    '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
                    '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
                    '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
                    '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
                    '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
                    '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
                    '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
					'@angular/material':'npm:@angular/material/bundles/material.umd.js',
                    '@angular/flex-layout':'npm:@angular/flex-layout/bundles/flex-layout.umd.js',
                    'ng2-md-datatable':'npm:ng2-md-datatable/ng2-md-datatable.umd.js',
                    'angular-sortablejs': 'npm:angular-sortablejs/dist/',
                    'sortablejs': 'npm:sortablejs/Sortable.js',
                    'rxjs': 'npm:rxjs'
                },
                packages: {
                    app: {
                        main: './main.js',
                        defaultExtension: 'js'
                    },
                    'angular-sortablejs': { main: 'index.js', defaultExtension: 'js' },
                    rxjs: {
                        defaultExtension: 'js'
                    }
                }
			});
			System.import('app')
					.then(null, console.error.bind(console));

**Comment by FlorKaucic** [comment]
Hi, @leerenold, just in case it helps you:
I was getting an error with SystemJS because of this:
```
'angular-sortablejs': 'npm:angular-sortablejs/dist/',
'sortablejs': 'npm:sortablejs/Sortable.js',
```
As in the last version it was trying to import `'sortablejs/Sortable.min'` 
Having `'sortablejs': 'npm:sortablejs/Sortable.js'` in the map means it's trying to look for `sortablejs/Sortable.js/Sortable.min` which in fact doesn't exists. 

I changed it to this:
```
'angular-sortablejs': 'npm:angular-sortablejs/dist/',
'sortablejs/Sortable.min': 'npm:sortablejs/Sortable.min.js',
```

I also got another error after that, but I found the fix, which I'll be uploading in a few minutes for @smnbbrv  to review. 

Hope it helps!

**Comment by leerenold** [comment]
@FlorKaucic . Thanks for your help . But I still get the same error.

System.config({
                paths: {
                    'npm:': 'lib/'
                },
                map: {
                    app: 'app',
                    ...
                    'angular-sortablejs': 'npm:angular-sortablejs/dist/',
                    'sortablejs/Sortable.min': 'npm:sortablejs/Sortable.min.js',
                    'rxjs': 'npm:rxjs'
                },
                packages: {
                    app: {
                        main: './main.js',
                        defaultExtension: 'js'
                    },
                    'angular-sortablejs': { main: 'index.js', defaultExtension: 'js' },
                    rxjs: {
                        defaultExtension: 'js'
                    }
                }
});

tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "types":["node","core-js"],
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "gulpfile.ts",
    "node_modules"
  ]
}
Most of the forum discusions werearound multi line comments . set Ts compiler to remove comments . No luck. Attached error image.
![error](https://cloud.githubusercontent.com/assets/17286159/25057087/3b97a7f6-212a-11e7-9936-2dac4d1eaa95.PNG)

**Comment by smnbbrv** [comment]
hi @leerenold 

maybe they mean comments should be removed on our side? They were enabled, but now I removed it. Could you check the version 2.0.4?

**Comment by leerenold** [comment]
hi @smnbbrv ,
Thanks for replying on this. Yes , they mean removing multi line comments from our end and also mentioning in tsconfig.json.
I am not sure whether any config to be added in tsconfig, because I am following everything said in the steps to be followed in angular-sortablejs.

**tsconfig.json:**

{
"compilerOptions": {
"target": "es5",
"module": "commonjs",
"moduleResolution": "node",
"sourceMap": true,
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
**"removeComments": true,**
"noImplicitAny": false,
"types":["node","core-js"],
"typeRoots": [
"node_modules/@types"
]

**systemjs config:** 

System.config({
                paths: {
                    'npm:': 'lib/'
                },
                map: {
                   ......
                    **'angular-sortablejs': 'npm:angular-sortablejs/dist/',
                    'sortablejs/Sortable.min': 'npm:sortablejs/Sortable.min.js',**
                   ....
                },
                packages: {
                    app: {
                        main: './main.js',
                        defaultExtension: 'js'
                    },
                    **'angular-sortablejs':
		  {
		    main: 'index.js',
		   defaultExtension: 'js'
		},**
                    rxjs: {
                        defaultExtension: 'js'
                    }
                }
});

**app.module.ts:**

import {SortablejsModule} from "angular-sortablejs";

imports:[....SortablejsModule...],

I am not sure what I am doing wrong. Is there anything to do with "es5" or "es6".

**Comment by smnbbrv** [comment]
Hi, I mean we removed the comments on sortable js side. Could you, please, run `npm update` and check if it is fixed ?

**Comment by leerenold** [comment]
Hi @smnbbrv ,
I got what you said in your previous comment. I updated angular-sortablejs. Using current version . I still face the issue .
**My package.json :** 
"angular-sortablejs": "^2.0.4",
"sortablejs": "^1.5.1",

**Comment by leerenold** [comment]
can anyone post the tsconfig.json for which it is working?

**Comment by Skubakoob** [comment]
I've been having the same problem with 2.04. When I look at what npm installs, it looks like uncompiled typescript?

**Comment by smnbbrv** [comment]
It is es6 not a typescript

**Comment by smnbbrv** [comment]
Please try v2.0.6

The issue should be gone

**Comment by Tamilstar** [comment]
The Server will be 404 found Loading Issue
