### ISSUE TITLE
Package on NPM requires user's module loader to understand ES2015 modules.

### ISSUE THREAD

**Issue by wrummler** [SortableJS/angular-sortablejs#48]
It seems like a recent PR to provide AoT compatibility overwrote the "normal" dist build config instead of providing an additional build config and integrating that into the package publishing pipeline. See [this commit](https://github.com/SortableJS/angular-sortablejs/commit/6b7a969c2c90d8d7ebedba349caf9623eb551490#diff-3e29c2829d321e59a8013b5756838223R4).

The result is that the npm package no longer works for non-AoT setups (as far as I can tell right now anyway). E.g. I get "Unexpected token export" at node_modules/angular-sortablejs/dist/index.js when loading my non-AoT app.

**Comment by smnbbrv** [comment]
@wrummler ahem, that sounds weird. AOT build usually cannot break a non-AOT one, from what I know. Could you, please, tell more about your environment? 

* Webpack or systemjs and the version of the one
* angular version
* angular-sortablejs version

It would also help to have a repo where the issue could be reproduced

**Comment by wrummler** [comment]
I applied the README instructions to the quickstart seed and got the same error as #44. Repo [here](https://github.com/wrummler/angular-sortablejs-issue-48).

I don't think this is a AoT/non-AoT issue at this point. I think these issues boil down to 6b7a969 introducing the requirement that the user's module loader understand ES2015 modules. For example, my non-AoT app is a very plain Electron/Angular setup (derived from `electron-forge init`'s Angular template) that simply uses Node's `require` to load modules. When it sees `export`, it doesn't recognize the token because Node doesn't yet provide built-in support for ES2015 modules. Similarly, when SystemJS sees it in e.g. the quickstart repo linked above, apparently it's trying to grab `traceur` to transpile it on-the-fly. This is part of the quickstart behavior:

```
Unable to load transpiler to transpile http://localhost:3000/node_modules/angular-sortablejs/dist/index.js
```

I made another [branch](https://github.com/wrummler/angular-sortablejs-issue-48/tree/workaround) that attempts to work around the issue by including configuration for `systemjs-plugin-traceur`. It eliminates the error in that example repo, but the behavior of the simple example included from this project's README seems incorrect, since the "See the result" items are not updated when the dragged items are.

Also, this workaround isn't available for my actual project, since we're not using SystemJS (or Webpack etc), just Node's `require` in Electron.

**Comment by wrummler** [comment]
I updated the issue title. Please consider this a suggestion to remove the requirement by including a CommonJS-compatible `main` entry in the distributed package.json and allowing ES2015 module users (e.g. those using AoT with Rollup) to configure their loader to point to a separate ES2015 build file also included with the distributed package. Thanks.

**Comment by smnbbrv** [comment]
that could be then the same issue as this one https://github.com/SortableJS/angular-sortablejs/issues/44

**Comment by smnbbrv** [comment]
@wrummler could you please check if v2.0.5 fixes the issue?

**Comment by smnbbrv** [comment]
fixed the second issue too. For some reason the change detection trigger was not done

**Comment by smnbbrv** [comment]
@wrummler thanks for the contribution! Check v2.0.6

**Comment by wrummler** [comment]
@smnbbrv Thanks, 2.0.5 fixed it for me.

Also, I don't have an AoT setup handy to double-check, but I think that AoT/rollup users can still use this new/reverted build if they update their rollup-config.js appropriately in the object passed to the invocation of the `commonjs` plugin in the `plugins` array. (It's been a long time since I used AoT, so YMMV.)
