### ISSUE TITLE
class binding not working after sort [class.className]="isClass"

### ISSUE THREAD

**Issue by vincent-cm** [SortableJS/angular-sortablejs#49]
className not appended after a sort complete.

**Comment by smnbbrv** [comment]
hi @vincent-cm 

could you please post the whole code? Ideally on plunkr, e.g. https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by smnbbrv** [comment]
@vincent-cm please check v2.0.6, the issue is probably fixed

**Comment by smnbbrv** [comment]
closed due to inactivity
