### ISSUE TITLE
Problem with grouping

### ISSUE THREAD

**Issue by f1lon** [SortableJS/angular-sortablejs#5]
If we use several sortable widget with a same group option,it renders correctly,but bounded model does not update.

**Comment by smnbbrv** [comment]
Hello @f1lon ,

could you please make a plunkr to reproduce the issue?

**Comment by xaph0n** [comment]
I'm also experiencing this issue.  Dragging within a single list updates the attached data without issue.  However, once I drag an item from one list to another it shows up in the dom in the correct place, but the dataset doesn't get updated. 

I'll see if I can put a plunkr together.

**Comment by xaph0n** [comment]
Heres a plunker:

[https://plnkr.co/edit/Q79NFBmFEHPJ2wkbegLc?p=preview](url)

**Comment by smnbbrv** [comment]
should be fixed by https://github.com/SortableJS/angular-sortablejs/pull/11 , try to explicitly update the version to 1.0.0: `npm install angular-sortablejs@1.0.0`. See the readme file for the usage hints

@xaph0n thank you for your time and for kicking my lazy ass. Please try the new version and let me know whether this is what you wanted that I can close the issue

**Comment by xaph0n** [comment]
That works a lot better!  Now I just need to open a bug on the main project.  Thanks for getting that fixed.

**Comment by smnbbrv** [comment]
@xaph0n you are welcome. Just a hint: before opening a bug in a main project try 1.15.0-rc1 version. This fixes some issues, maybe it is already fixed there

**Comment by xaph0n** [comment]
Thanks for the hint, I was just setting up a plnkr and that looks to be fixed as well.  I'm a little new to npm, but if I include the 1.15 version in my package.json file, it will use that version over the one specified in angular-sortablejs' package.json?

**Comment by smnbbrv** [comment]
@xaph0n yes, exactly. If you don't specify the version, npm tries to understand across all dependencies the most fitting one. If you specify it, it takes yours and will throw you a warning if your version is lower than required. You can check the version you have by going to the node_modules/sortablejs/package.json to ensure you have a correct one
