### ISSUE TITLE
problem with latest angular-cli

### ISSUE THREAD

**Issue by deinega** [SortableJS/angular-sortablejs#51]
I just updated angular-cli to the latest version... Now I cant build my project with sortablejs:

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in node_modules/@angular/core/core.d.ts, resolving symbol SortablejsModule in node_modules/angular-sortablejs/dist/src/sortablejs.module.d.ts, resolving symbol SortablejsModule in node_modules/angular-sortablejs/dist/src/sortablejs.module.d.ts

Can you please help?

**Comment by YamanSehzade** [comment]
Hi deinega, could you solve this problem ?

**Comment by deinega** [comment]
Hi. I solved it somehow... Thanks!

**Comment by YamanSehzade** [comment]
i have same problem. Could you help me ?

**Comment by deinega** [comment]
I don't remember what I did, but I think I didn't downgrade cli version.

**Comment by smnbbrv** [comment]
hi @YamanSehzade 

have you found a solution for that?

**Comment by YamanSehzade** [comment]
hi @smnbbrv, i gave up using sortablejs.

**Comment by wermerb** [comment]
Hi guys,
I have a fix for this issue. I already added a PR, but in the meantime you can check there for the temporary fix for your selves.
