### ISSUE TITLE
Touch Event displays cloned item

### ISSUE THREAD

**Issue by ajinkyau** [SortableJS/angular-sortablejs#52]
When trying to click on an element which has sortablejs applied, the click goes through but it is also, displaying the cloned item on touch of the element.

Using the dealy property from Sortablejs does not work on touch devices and there are issues related to the same on SortableJs library.

Version:
angular-sortablejs: ^1.3.2
sortablejs: ^1.4.2 (which is used internally by angular-sortablejs since I am using angular 2)

Browser tested on: Chrome (59.0.3071.125) (Android Tablet)

Please refer attached video from the zip file for the same.
[touch-clone-error.zip](https://github.com/SortableJS/angular-sortablejs/files/1241771/touch-clone-error.zip)

**Comment by smnbbrv** [comment]
hi @ajinkyau 

as long as this is an original library problem we can't do a lot here - this library just enables some angular 2 helpers for the original library, nothing more...

**Comment by smnbbrv** [comment]
Closing as not related to this particular repository
