### ISSUE TITLE
Touch Event Listeners as Passive

### ISSUE THREAD

**Issue by malorus** [SortableJS/angular-sortablejs#53]
Hi, as I'm using this angular-implementation of sortablejs I want to ask my question here. While testing sortablejs with chrome 60, I recognised that when toggling to the device toolbar (Galaxy S5 for example) and using then a touch event to sort a list, chrome throws the following warning:

>[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

Any idea how to deal with it?

**Comment by smnbbrv** [comment]
hi @malorus 

This project does not add any `preventDefault` calls (just searched for it). I'm sorry, but I am afraid this is an issue of the original sortablejs library. Most likely you should point your question there.

**Comment by malorus** [comment]
Hey @smnbbrv, thanks for your reply. I have already opened an issue there. So hopefully they will check it. I will close it here.
