### ISSUE TITLE
Items cannot be placed in empty groups

### ISSUE THREAD

**Issue by felipeallmountain** [SortableJS/angular-sortablejs#54]
Hi

I'm working on a sortable component between groups. Everything works good when I'm moving items between groups, but I'm not able to put items to empty groups that had items before. I'm setting the 'group', 'draggable' and 'handle' property for this issue, also, I'm setting the group with min-height options to have a good space to drop the item, but no results. Any hints for that?? 

`this.chipContainerOptions  = {
      group: 'chipgroup',
      animation: 275,
      draggable: '.chip-item',
      handle: '.attribute-chip__content'
 };`

Thanks in advance!!

**Comment by smnbbrv** [comment]
Hi, this looks weird. Could you try the really same without angular (with raw sortablejs and some fiddle)? Whether it persists, it is an original sortablejs problem. When not, then it is interesting, but looks the problem is somewhere on angular side.

**Comment by krasznaidavid** [comment]
I have the same problem. Is there any update on this?

**Comment by krasznaidavid** [comment]
Actually, I got it working by setting a `min-height` to the item's container. So it's all good!

**Comment by smnbbrv** [comment]
Cool! Then I close the issue for inactivity and actually a solution 👍
