### ISSUE TITLE
Doesn't work with latest version of angular cli 

### ISSUE THREAD

**Issue by RaedsLab** [SortableJS/angular-sortablejs#59]
Using angular/cli 1.1.2

I get the following error  `Can't bind to 'sortablejs' since it isn't a known property of 'div'`

"sortablejs": "^1.6.1"
"angular-sortablejs": "^2.0.6"

PS: Angular moved away from "systemjs.config.js" so I'm not sure how to include the lib

**Comment by smnbbrv** [comment]
Please read carefully: if you have no systemjs - do nothing. Webpack (which is a basis of angular-cli) does everything for you.

Your message says that you did not import the Sortablejs into the module where you are about to use it.
