### ISSUE TITLE
2.2.0 breaks 2.1.0

### ISSUE THREAD

**Issue by dolanmiu** [SortableJS/angular-sortablejs#63]
I got an error when I ran `npm install`. I have version `^2.1.0` which resolves to `2.2.0`:

```
No provider for InjectionToken Global config for sortablejs
```

Turns out there is a new way to import:

https://github.com/SortableJS/angular-sortablejs/commit/9f753ea7b3a5466cff85db6e99b34f35eaceb7c7

Breaking change, `2.1.0` is not compatiable with `2.2.0`

I use sortableJS in a lot of my projects at version `^2.1.0`, and it broke all of them! I guess next time, I cannot use the carrat `^`

**Comment by fu3l** [comment]
Yup seeing the same problem and as you've suggested, pinning to 2.1.0 has resolved the problem for now.

**Comment by smnbbrv** [comment]
This could be resolved by adding `Sortablejs.forRoot({})` to your app module. However I think I will fix it today

**Comment by smnbbrv** [comment]
try to update to @2.2.1 - should be fixed now

**Comment by fu3l** [comment]
Perfect, 2.2.1 is working as before.

I did notice the change in the README.MD to include the `forRoot({})` but hadn't tried it as the downgrade worked fine.
Thank you.
