### ISSUE TITLE
Can't resolve 'sortablejs/Sortable.min'

### ISSUE THREAD

**Issue by sarnecki-cic** [SortableJS/angular-sortablejs#64]
I guess there's a problem with path in sortablejs.directive.js.
My Angular CLI can't compile project because of it.

EDIT: I've found the issue, Sortablejs is not set as a peer dependency and you have to install it by yourself.

**Comment by smnbbrv** [comment]
First of all the installation guide tells explicitly that you need to install sortablejs separately.

Secondly it **is set up as peer dependency** , see https://github.com/SortableJS/angular-sortablejs/blob/master/package.json .

**Comment by smnbbrv** [comment]
Closing as solved
