### ISSUE TITLE
Missing certain sortablejs options in sortablejs-options.ts intrface

### ISSUE THREAD

**Issue by tibinvpaul** [SortableJS/angular-sortablejs#65]
Hey,

I am trying to use `preventOnFilter` option of `sortablejs` and just figured out that this is missing in the `sortablejs-options.ts` interface (https://github.com/SortableJS/angular-sortablejs/blob/master/src/sortablejs-options.ts). Is it something not supported or we need to update the interface with all available options? Thanks in advance.

**Comment by smnbbrv** [comment]
I guess this is some new option that was not existing when the lib was created; this should be working regardless of the interface. Could you make a pull request adding the property?

**Comment by tibinvpaul** [comment]
Yeah, this is working regardless of the interface. I will submit a PR. Thanks.

**Comment by tibinvpaul** [comment]
Hey @smnbbrv - please find the PR [here](https://github.com/SortableJS/angular-sortablejs/pull/66).

**Comment by smnbbrv** [comment]
Should be available from angular-sortablejs@2.2.2 on
