### ISSUE TITLE
Is onMove logic implemented?

### ISSUE THREAD

**Issue by Axel186** [SortableJS/angular-sortablejs#74]
Hi, I am trying to use the `onMove` event, but not getting any callback.

I can see the method added into the interface, but can't find the implementation...

This is still in progress? 

My idea is to detect and to style the "dropable" element, when I drag item over it.

**Comment by smnbbrv** [comment]
Hi @Axel186 

could you post the code you tried? What is the meaning of

> not getting any callback

?

**Comment by Axel186** [comment]
OK, obliviously, I used this event in a wrong way :smile:.

Here is an example:
```
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  styles: [
    '.items1{ width:300px; height:300px; border:1px solid red; }'
  ],
  template: `
    <h2>Drag / drop the item</h2>
    <h3>Drop here</h3>
    <div class="items1 droppable" [sortablejs]="dropped" [sortablejsOptions]="optionsDrop" runInsideAngular="true"></div>
    <h3>list 2</h3>
    <div class="items2 list" [sortablejs]="list" [sortablejsOptions]="optionsList" runInsideAngular="true">
      <div *ngFor="let item of list">{{ item }}</div>
    </div>
  `
})
export class AppComponent {
  dropped = [];
  list = ['a', 'b', 'c', 'd', 'e'];

  optionsList = {
    group: 'test',
    onMove: () => console.log('Option List - onMove')  // <== Getting the Event here!
  };

  optionsDrop = {
    group: 'test',
    onMove: () => console.log('Options Drop - onMove')  // <== I was expecting callback here.
  };
}`
```

As you can see, the idea here is to have a list of elements and a "droppable" zone.
I was listening for event on Droppable element, but it triggered on the List element.

Sorry for that mistake and thank you for awesome work :+1: .

**Comment by smnbbrv** [comment]
No problem :) the issue can be closed then?
