### ISSUE TITLE
onAdd is called before data binding is done

### ISSUE THREAD

**Issue by Dumpen** [SortableJS/angular-sortablejs#75]
The documentation states "If you will add your own event handlers (inside of the options object) they will **be called right after the data binding is done.**", the problem however is the "onAdd" event is called before data binding is done meaning the model is not updated at that time, the "onUpdate" event for some reason works though.

Example: https://embed.plnkr.co/70deYXEpG0MENPw0UWCa/

Let me know if you need more information.

**Comment by smnbbrv** [comment]
Hi @Dumpen 

`onAdd` does not make any binding, it postpones it until the `onRemove` happens. See https://github.com/SortableJS/angular-sortablejs/blob/8f669e936790352ebb7360b199576ac5d9bea614/src/sortablejs.directive.ts#L126

The events are called in the same manner the original sortablejs calls them. And this is actually what we have to live with in this library, see the comment here https://github.com/SortableJS/angular-sortablejs/blob/master/src/sortablejs.service.ts ; this is not supposed to be changed.

You can use the same approach to handle `onAdd` after `onRemove` is done (see the links above): create a service that remembers what the current `onAdd` should perform and run it when the `onRemove` happens.

**Comment by smnbbrv** [comment]
updated the readme to reflect this as well

**Comment by smnbbrv** [comment]
@Dumpen actually handling events on your own is a pretty much hell. A better way is to just use FormArray for each list and listen to `valueChanges` events.

**Comment by smnbbrv** [comment]
After some while I changed my mind: you are right, it is ridiculous. Check the @2.5.0 (), it should emit the `onAdd` in a proper order; added `onAddOriginal` to emit original event as well. Please let me know if you have problems.

**Comment by Dumpen** [comment]
Thanks, it works as expected now 👍
