### ISSUE TITLE
Vertical scroll,

### ISSUE THREAD

**Issue by Tejani** [SortableJS/angular-sortablejs#77]
I am facing issue while card move from bottom to top. normal card move is working

**Example**
I have 100 card and I am moving card from 100 to 5 but not able to move because vertical scroll is not working,

**Expected** 
If I select bottom card and move on top then it should be vertical scroll.

**Comment by smnbbrv** [comment]
Hi @Tejani 

what is supposed to be scrollable in your example? Is it body or some div that has `overflow: scroll` or `auto`?

Do you have some fixed area above the scrollable element? If yes look how https://smnbbrv.github.io/angular-sortablejs-demo/custom-options (drag items in Autoscroll with fixed navbar) is implemented.

If it is not body and not a position: fixed element issue please provide a plunkr reproducing the problem

**Comment by Tejani** [comment]
Hi @smnbbrv 
Thanks for your replay.
I didn't have mentioned `overflow:scroll or auto`

I just put `<div [sortablejs]="listDetail"  class="listing-area clearfix">` and inside I have for loop which load the bulk of data.

Should I have to mention `overflow:scroll or auto`

**Comment by Tejani** [comment]
@smnbbrv 

Thanks for your reference "https://smnbbrv.github.io/angular-sortablejs-demo/custom-options" it's work for me.

**Comment by smnbbrv** [comment]
You are welcome! 👍 Happy to help!
