### ISSUE TITLE
Problem when sorting linked columns

### ISSUE THREAD

**Issue by Kroenen62** [SortableJS/angular-sortablejs#78]
Hello, 

When I select an item in the right column, the shadow goes to the left column before returning to the right column....

[example](https://plnkr.co/edit/uncIf44tviH4ntTQMHel?p=preview)

**Comment by Kroenen62** [comment]
![bug](https://user-images.githubusercontent.com/12496925/34712337-c782aaf0-f522-11e7-968f-adc0579d7743.gif)

**Comment by smnbbrv** [comment]
Hi @Kroenen62 

that looks weird. The plunkr you provide works really well on my computer (Mac + Chrome) and I cannot reproduce the behavior from the gif. Could you tell more about your browser / os?

**Comment by Kroenen62** [comment]
Hi @smnbbrv 

I use chrome v63.0.3239.132 on windows 10 1709.
I just tested on mozilla and edge, there is no bug ....

**Comment by smnbbrv** [comment]
windows 10 and chrome of the same version... I still cannot reproduce it...

**Comment by smnbbrv** [comment]
could you try to disable all the extensions? Maybe one of them gives that side effect... However that does not explain electron problem

**Comment by Kroenen62** [comment]
I have try to : 
- disable all the extensions
- the guest mode
- reinstall chrome 
- install chromium
- chrome on windows server 2012r2
- chrome on windows 7

 and i have this bug everywhere.... i not understand the reasons of this bug.

**Comment by smnbbrv** [comment]
this looks similar to the original library issue https://github.com/RubaXa/Sortable/issues/907 ; they actually also had a problem to reproduce it

Try to replace inline-block on the container with e.g. float-left, maybe it helps.

**Comment by Kroenen62** [comment]
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/12496925/34765504-f9b57942-f5f1-11e7-9278-8b5421f1f76d.gif)

it has no changes

**Comment by Kroenen62** [comment]
Hi,
I have solved this probleme, when i set this config.

`sortbalejsOption = {
      group: 'test',
      ...., 
      animation:150,
      forceFallback : true
    };`

**Comment by smnbbrv** [comment]
Super! Probably I need to force this setting; I don't really see any point in not enabling it all the time
