### ISSUE TITLE
How to handle, array of objects with different structures?

### ISSUE THREAD

**Issue by abhishekdgeek** [SortableJS/angular-sortablejs#79]
Hi all,

I am migrating my app from ng2-dnd to angular-sortablejs because of performance issues. I have a requirement that has multiple drag-able items and one drop-able box which can also be sortable. The plugin is working fine for array of objects while sorting but I do not get my JSON data anywhere, also I need to process the data as the JSON needs to be remapped when I am moving an object from a list of drag-able items to drop-able box.

I understand this plugin copies HTML but I am looking for JSON data alone.

Thanks,
Abhishek.

**Comment by smnbbrv** [comment]
Hi @abhishekdgeek 

I don't really get what is the problem. Could you create a plunkr that reproduces the problem? Or at least give some version of your input and expected output here?

**Comment by abhishekdgeek** [comment]
Okay, there are 2 containers A and B with different HTML markups and are array of different arrays. Container A is as follows:

`containerA: [ {itemId: 1, key: value}, {itemId: 2, key: value}, {itemId: 3, key: value}]`
All values are nested JSON objects.

`containerB: [ {id: 1, key1: value1, key2: value2}, {id: 2, key1: value1, key2: value2}, {id: 3, key1: value1, key2: value2}]`

Now when I move any item from containerB to containerA then I need to process containerB's content and HTML to match that of containerA.

Also ContainerA must be able to rearrange it's positions i.e. what this plugins do but I do not get any value to process.


What I am building is like a real time drag and drop along with sorting and have to handle success and error cases of API response.


Hope this helps, many thanks.

**Comment by smnbbrv** [comment]
This library does the values mapping; that's actually the purpose of this library.

If I understand you right, you want to get some events when the data gets changed (after it is sorted / added / removed).

You have two options:
- you can subscribe to any of the original Sortablejs events like onAdd, onRemove and onUpdate, see the example here https://smnbbrv.github.io/angular-sortablejs-demo/custom-options (Events)
- transform the values into FormArray and subscribe to the changes there

After the events get triggered you can do whatever you want with the A / B data.

Does this help to solve the problem?

**Comment by smnbbrv** [comment]
answered => closing

**Comment by RFMV34** [comment]
I have same issue and I do not know how to solve it using onAdd... I have for example object in container A with this structure {name: 'Filip', age: 25} and after drop into container B I want to change object structure, for example remove age or something so object should be {name: 'Filip'}
