### ISSUE TITLE
Error in updating model with multiple sortable

### ISSUE THREAD

**Issue by a5hik** [SortableJS/angular-sortablejs#8]
When you have a multiple sortable options and provide the model as `[sortablejs]="modelData"` then you get an error, when you do few drag drop across lists. 

this seems to work only when you drag drop with in the same list. looking at the lib the array slice is designed to update for single list.

**Comment by smnbbrv** [comment]
hi @a5hik 

I'll have a look when I have time... Still pull requests are always welcome!

**Comment by EinArzt** [comment]
Would love to see this too. If you need any help, let me know!

**Comment by smnbbrv** [comment]
@EinArzt @a5hik are this issue and issue #5 the same?

**Comment by smnbbrv** [comment]
should be fixed by https://github.com/SortableJS/angular-sortablejs/pull/11 , try to explicitly update the version to 1.0.0: `npm install angular-sortablejs@1.0.0`. See the readme file for the usage hints
