### ISSUE TITLE
No access to dataTransfer onEnd event object

### ISSUE THREAD

**Issue by seanlawrenz** [SortableJS/angular-sortablejs#81]
I'm trying to receive customizable data. My sortable objects are dynamic and I would like to get the object back on a drop. There is a setData option, but it doesn't seem to do anything to the final event object.

**Comment by smnbbrv** [comment]
Hi

Could you please post what you tried so far? Preferably some plunkr

**Comment by seanlawrenz** [comment]
I was able to find a work around for this, by injecting the data object into the event object using a shared services and working with the overridenOptions method that you have. 

If I ever get some free time I'll do a plunkr, but not sure when that will be. I wouldn't be made if you closed this.

**Comment by smnbbrv** [comment]
Good that something worked! Thanks!
