### ISSUE TITLE
Can't remove newly added element

### ISSUE THREAD

**Issue by choEnnova** [SortableJS/angular-sortablejs#82]
When removing newly added element, the UI is not updated.
See following
https://plnkr.co/edit/WcK824ulv9jOEOLODG3l?p=preview

Drag in new item from list1 to list2, and click it to remove. The UI is not updated. (Only dragged items is not updated).

**Comment by smnbbrv** [comment]
interesting, can confirm that behavior.

As a quick fix you can try [detectChanges](https://angular.io/api/core/ChangeDetectorRef) or `applicationRef.tick` when remove is complete

**Comment by Dumpen** [comment]
Is there a fix you can apply @smnbbrv ? The detectChanges works but is kinda dirty.

**Comment by smnbbrv** [comment]
should be fixed with the latest version. Cannot validate plunkr (does not run for me anymore)
