### ISSUE TITLE
.sortable-drag is added on a HTML focus

### ISSUE THREAD

**Issue by borriej** [SortableJS/angular-sortablejs#84]
[x]Bug

Angular2+

When having a sortablejs on a reactive form array (with simple options).. i click on a item.. Im not dragging.. so it's just a HTML focus on the item in the array. The class .sortable-drag is added to the item, and does not remove itself untill it drag&drop it again.

So in my case. I've styled .sortable-drag with dotted line. So the dotted line comes visble on a simple focus, instead of dragging. This is confusing for the user.

**Comment by smnbbrv** [comment]
Hi, please post a bug on original https://github.com/RubaXa/Sortable library. I'm pretty sure it's coming from there; this library cares about the binding to the model only. Feel free to reopen it in case you are sure this appears only in angular apps.
