### ISSUE TITLE
How to disable sorting for a single entry in the list?

### ISSUE THREAD

**Issue by Haladria** [SortableJS/angular-sortablejs#86]
Is it possible to disable sorting for one of the entries in the list?

**Comment by smnbbrv** [comment]
yes, with `filter` or `draggable` options from https://github.com/RubaXa/Sortable

**Comment by smnbbrv** [comment]
However it does not mean that other items could not go above or below the disabled one

**Comment by smnbbrv** [comment]
answered => closing
