### ISSUE TITLE
Does this sort the actual items array or just the DOM elements?

### ISSUE THREAD

**Issue by jaichandra** [SortableJS/angular-sortablejs#89]
May be a naive question, but wanted to confirm, when items in a list are sorted using drag, does this library sort the array that it is bound to or just rearrange the DOM elements. I guess, angular databinding will kick in anyway and sort the array. But Im seeing inconsistent behavior here. Sometimes I see the array sorted, and sometimes its not. Not sure if I'm missing anything.

**Comment by dbrezoev** [comment]
Hi, maybe the demo answers your question. See here: https://smnbbrv.github.io/angular-sortablejs-demo/sortable-array. 'The actual model' section.

**Comment by smnbbrv** [comment]
@jaichandra 

this is a hard-to-answer question because I would need to comment on every line of the code of the library.

What is the particular problem you are facing?

**Comment by jaichandra** [comment]
@smnbbrv Thanks. It does sort the array as well. I think the angular bindings take care of this automatically. It was some issue with my app code. Closing this.
