### ISSUE TITLE
how disabled sort Across variable  true or false ?

### ISSUE THREAD

**Issue by Ahmed747474** [SortableJS/angular-sortablejs#90]
<button mat-icon-button class="locks" (click)="UnLock()">
           <mat-icon aria-label="Example icon-button ">{{ic}}</mat-icon>
      </button>
    <mat-list class="para" [sortablejs]='data' [sortablejsOptions]="eventOptions" >
.......
i need disabled  sort from button

**Comment by smnbbrv** [comment]
you need to update the `eventOptions.disabled` to the proper value and create a new `eventOptions` object to notify the library that it was changed.

```ts
Unlock() {
  this.eventsOptions = { ...this.eventsOptions, { disabled: true } };
}
```

**Comment by Ahmed747474** [comment]
thank You

**Comment by smnbbrv** [comment]
yw :)
