### ISSUE TITLE
sortablejsCloneFunction documentation

### ISSUE THREAD

**Issue by kuba-010** [SortableJS/angular-sortablejs#93]
Hi,

Just a minor thing around the documentation for the clone function. Had me scratching my head for a little bit so might just save someone some pain down the line!

In the documentation you have:

```
myCloneImplementation(item) {
    return item; // this is what happens if sortablejsCloneFunction is not provided. Add your stuff here
  }
```

If you try to use **this** in the myCloneImplementation this will be null - so you can't use a service in the component. I.e. 

`this.myservice.cloneItem(item); `

won't work

Instead myCloneImplementation function should be an arrow function which will correcty inherit the parent context:
```
myCloneImplementation = (item) =>{
    return item; // this is what happens if sortablejsCloneFunction is not provided. Add your stuff here
  }
```

This makes **this** available, so I could the do my this.myservice.cloneItem(item); call now
i.e
```
myCloneImplementation = (item) =>{
    return this.myservice.cloneItem(item); 
  }
```

**Comment by smnbbrv** [comment]
done, thanks
