### ISSUE TITLE
Need an angular model property in OnCollectionUpdate event

### ISSUE THREAD

**Issue by nkesar** [SortableJS/angular-sortablejs#95]
I have created these draggable items in a parent ngFor. So basically I have groups of these draggable items and they can only be dropped inside the same group (so no cross group drag and drop). I need to know which group has been updated but OnCollectionUpdate() event only gives me old index and new index. How can I find which parent group has been effected? Is there a way to pass any angular model property to this event?

Thanks

**Comment by smnbbrv** [comment]
hi @nkesar 

it's not really clear what you mean. Please post a stackblitz reproducing the issue.

Also, it is not clear what angular model do you mean to add to the event.
