### ISSUE TITLE
how to drap and sort only from a button inside the component

### ISSUE THREAD

**Issue by hamzafaouzi** [SortableJS/angular-sortablejs#96]

**Comment by smnbbrv** [comment]
Please clarify your question and provide the plunkr / stackblitz with an example

**Comment by zeuspatriot** [comment]
@smnbbrv , I believe what @hamzafaouzi ment, is to implement Handle -- special directive that will indicate that only this DOM element should fire drag events (or rather events only from this element should be listened to)

**Comment by smnbbrv** [comment]
ah, but that's already in there. Use `handle` property from https://github.com/RubaXa/Sortable
