### ISSUE TITLE
Style of dragged items

### ISSUE THREAD

**Issue by beuen** [SortableJS/angular-sortablejs#99]
Hi, 

we use angular-sortablejs to have a board with cards. Technical wise anything works fine, but as we have divs with scrollable overflow the style of the dragged carry cards gets broken. If I drag them via touch it just works fine. If I drag them with mouse the complete card only contains of parts of the picked item or with near background only.

It is not about the "ghost" class, this we hided by ourselfs. Only about those "carry" cards attached to the mouse/pointer. 

Does anybody know those kinds of styling bugs and how to fix it? 

![image](https://user-images.githubusercontent.com/38457412/38859183-c423058c-422d-11e8-8585-5f9074033252.png)

**Comment by smnbbrv** [comment]
Hi @beuen 

it's hard to say what' wrong without an example... Could you create one on stackblitz?

**Comment by beuen** [comment]
Thx 4 fast response. It may take some time but I´ll try to create one. First just wanted to ask if somebody knows this issue on divs with overflow: scroll

**Comment by smnbbrv** [comment]
Most likely this is a problem of original sortable library because I don't really see any connection with angular here... Maybe it is worth asking it there.

**Comment by beuen** [comment]
Thank you for the response. I opened an issue on the original library. This one can be closed then I guess. [https://github.com/RubaXa/Sortable/issues/1313](url)
